[tool.black]
line-length = 79
exclude = """
(
  /(
      /.git
    | /.mypy_cache
    | /.venv
    | /.pytest_cache
  )/
)
"""


[tool.isort]
force_single_line = true
profile = "black"
multi_line_output = 3


[tool.mypy]
exclude ="""/resources/"""
python_version = 3.7
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
show_error_context = true
show_error_codes = true
sqlite_cache = true
pretty = true
color_output = true


[[tool.mypy.overrides]]
module = [
    "psycopg2",
    "devtools",
]
ignore_missing_imports = true
